web:  
  build: .
  env_file: .env
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/app
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis
sidekiq:  
  build: .
  env_file: .env
  command: bundle exec sidekiq
  volumes:
    - .:/app
  links:
    - postgres
    - redis
postgres:
  image: postgres:latest
  ports:
    - "5432"
redis:  
  image: redis
  ports:
    - "6379"